suppressMessages({library(igraph);library(ggplot2)}); set.seed(123)
DATA<-"replication/extended/output/empirical_data"; OUT<-"replication/extended/output/empirical"; net<-"atop"; FIG<-"manuscript/figures"
S<-readRDS(file.path(DATA,sprintf("%s_series.rds",net))); U<-readRDS(file.path(DATA,sprintf("%s_union.rds",net)))
P<-readRDS(file.path(OUT,sprintf("%s_partitions.rds",net)))$partitions; yrs<-S$years
G<-lapply(seq_along(S$graph_layers),function(k) igraph::delete_vertices(S$graph_layers[[k]],which(!U$present[[k]])))
deg<-lapply(G,function(g){setNames(igraph::degree(g),V(g)$name)})
nm<-c("2"="USA","20"="CAN","200"="UK","220"="FRA","325"="ITA","211"="BEL","210"="NLD","212"="LUX","385"="NOR","390"="DEN","395"="ICE","235"="POR","260"="FRG","350"="GRC","640"="TUR","230"="SPN","365"="USSR","290"="POL","265"="GDR","315"="CZE","310"="HUN","360"="ROM","355"="BUL","255"="GER","300"="AUH")
systems<-list(ColdWar=list(win=c(1955,1989),yr=1985,A=list(name="NATO",codes=c("2","20","200","220","325","211","210","212","385","390","395","235","260","350","640","230")),B=list(name="Warsaw Pact",codes=c("365","290","265","315","310","360","355"))),PreWWI=list(win=c(1908,1914),yr=1913,A=list(name="Triple Alliance",codes=c("255","300","325")),B=list(name="Triple Entente",codes=c("220","365","200"))))
meth<-c("DynMux Jaccard r1","DynMux Overlap r1","DynMux multislice r1","multinet GLouvain","Cross-sectional + Hungarian","Pooled Leiden")
mlab<-c("Jaccard","Overlap","multislice","multinet","CS+Hungarian","Pooled"); mlab2<-c("Jaccard","Overlap","multi-\nslice","multi-\nnet","CS +\nHungarian","Pooled")
assign_year<-function(m,t,sA,sB){a<-P[[m]][[t]]; dg<-deg[[t]]; act<-function(cs) cs[sapply(cs,function(c)(c%in%names(a))&&(c%in%names(dg))&&dg[[c]]>0)]; Aa<-act(sA$codes); Ba<-act(sB$codes); if(length(Aa)<2||length(Ba)<2)return(NULL); cA<-a[Aa]; cB<-a[Ba]; pA<-names(sort(table(cA),decreasing=TRUE))[1]; pB<-names(sort(table(cB),decreasing=TRUE))[1]; mg<-(pA==pB); df<-rbind(data.frame(code=Aa,bloc=sA$name,comm=as.character(cA),stringsAsFactors=FALSE),data.frame(code=Ba,bloc=sB$name,comm=as.character(cB),stringsAsFactors=FALSE)); df$plur<-ifelse(df$bloc==sA$name,pA,pB); df$correct<-(df$comm==df$plur)&!mg; df$merged<-mg; df}
SS<-list()
for(sk in names(systems)){sy<-systems[[sk]]; for(mi in seq_along(meth)){tot<-0;mis<-0;mf<-0; for(y in sy$win[1]:sy$win[2]){t<-which(yrs==y); if(!length(t))next; d<-assign_year(meth[mi],t,sy$A,sy$B); if(is.null(d))next; tot<-tot+nrow(d); mis<-mis+sum(!d$correct); if(any(d$merged))mf<-mf+1}; SS[[length(SS)+1]]<-data.frame(period=sk,method=mlab[mi],pct=round(100*mis/tot,1),merge_yrs=mf,n=tot)}}
SS<-do.call(rbind,SS); cat("=== misplacement over full window ===\n"); print(SS,row.names=FALSE)
tileplot<-function(sk){sy<-systems[[sk]]; t<-which(yrs==sy$yr); rows<-list(); for(mi in seq_along(meth)){d<-assign_year(meth[mi],t,sy$A,sy$B); if(is.null(d))next; d$method<-mlab[mi]; rows[[length(rows)+1]]<-d}; D<-do.call(rbind,rows); D$cat<-ifelse(D$merged,"Merged (no separation)",ifelse(D$correct,D$bloc,"Misplaced")); D$state<-nm[D$code]; ordc<-c(sy$A$codes,sy$B$codes); ordc<-ordc[ordc%in%D$code]; D$state<-factor(D$state,levels=rev(nm[ordc])); D$method<-factor(D$method,levels=mlab); cat("\n=== ",sk,sy$yr," misplaced states ===\n"); for(mm in mlab){dd<-D[D$method==mm&!D$correct,]; cat(sprintf("%-14s: %s\n",mm,if(nrow(dd))paste(unique(dd$state),collapse=" ")else"(none)"))}; cols<-setNames(c("#2c7fb8","#d7301f","#000000","#8856a7"),c(sy$A$name,sy$B$name,"Misplaced","Merged (no separation)")); p<-ggplot(D,aes(method,state,fill=cat))+geom_tile(color="white",linewidth=0.5)+scale_fill_manual(values=cols,name="Assigned bloc",drop=FALSE)+scale_x_discrete(labels=mlab2)+labs(title=sprintf("%s (%d): recovered blocs by algorithm",sk,sy$yr),subtitle=sprintf("True blocs: %s (blue) vs %s (red). Black = state placed in neither.",sy$A$name,sy$B$name),x=NULL,y=NULL)+geom_hline(yintercept=length(sy$B$codes[sy$B$codes%in%D$code])+0.5,color="grey40",linetype="dashed")+theme_minimal(base_size=12)+theme(axis.text.x=element_text(lineheight=0.9),panel.grid=element_blank(),legend.position="right"); ggsave(file.path(FIG,sprintf("fig_blocs_%s.png",sk)),p,width=8,height=6,dpi=150); cat("saved fig_blocs_",sk,".png\n",sep="")}
tileplot("ColdWar"); tileplot("PreWWI")
SS$period<-factor(SS$period,levels=c("ColdWar","PreWWI"),labels=c("Cold War 1955-1989","Pre-WWI 1908-1914")); SS$method<-factor(SS$method,levels=mlab)
p2<-ggplot(SS,aes(method,pct,fill=method))+geom_col(show.legend=FALSE)+facet_wrap(~period)+scale_x_discrete(labels=mlab2)+labs(title="States not in correct historical bloc",y="Misplaced (% of coded state-years)",x=NULL)+theme_minimal(base_size=12)+theme(axis.text.x=element_text(lineheight=0.9),panel.grid.major.x=element_blank())
ggsave(file.path(FIG,"fig_blocs_summary.png"),p2,width=9,height=5,dpi=150); cat("saved fig_blocs_summary.png\n")
